sonar.projectKey=eclipse-ecsp_uidam-portal
sonar.organization=eclipse-ecsp
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=coverage/**,dist/**,node_modules/**
