name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'The name of the Docker image'
        required: true
        type: string
      image_tag:
        description: 'The tag for the Docker image'
        required: true
        type: string
      registry:
        description: 'The container registry URL'
        required: true
        type: string
      username:
        description: 'The username for the container registry'
        required: true
        type: string
      password:
        description: 'The password for the container registry'
        required: true
        type: string
      context_path:
        description: 'docker context path'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
           name: ${{ inputs.image_name}}-${{ inputs.image_tag }}.jar
           path: ${{ inputs.context_path}}/target/${{ inputs.image_name}}-${{ inputs.image_tag }}.jar

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ inputs.registry}}:${{ inputs.image_name }}

      - name: Build and push Docker image for API Gateway
        id: push-image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ inputs.context_path}}
          file: ${{ inputs.context_path}}/Dockerfile
          push: true
          tags: ${{ input.registry }}/${{ inputs.image_name}}:${{ inputs.image_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PROJECT_JAR_NAME=${{ inputs.image_name}}-${{ inputs.image_tag }}
            API_WAR_NAME=${{ inputs.image_name}}
            PROJECT_JAR_VERSION=${{ inputs.image_tag }}
