name: SonarCloud Analysis

on:
  workflow_call:
    inputs:
      java_version:
        description: 'The Java version to use'
        required: false
        type: string
        default: '17'
      sonar_project_key:
        description: 'The SonarCloud project key'
        required: true
        type: string
        default: ${{ github.repository.replace('/', '_') }}
      sonar_organization:
        description: 'The SonarCloud organization'
        required: false
        type: string
        default: ${{ github.repository_owner }}
    secrets:
      token:
        required: true

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Sonar is enabled
        id: sonar-check
        run: |
          if [[ "${{ secrets.SONAR_TOKEN }}" == "" ]]; then
            echo "SONAR_TOKEN is not set. Skipping Sonar analysis."
            echo "sonar_enabled=false" >> $GITHUB_ENV
          else
            echo "SONAR_TOKEN is set. Sonar analysis will be performed."
            echo "sonar_enabled=true" >> $GITHUB_ENV
          fi
      - name: Checkout code
        if: ${{ env.sonar_enabled == 'true' }}
        uses: actions/checkout@v4

      - name: Set up JDK
        if: ${{ env.sonar_enabled == 'true' }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: zulu
          cache: maven

      - name: Cache Maven dependencies
        if: ${{ env.sonar_enabled == 'true' }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run SonarCloud Analysis
        if: ${{ env.sonar_enabled == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.token }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=${{ inputs.sonar_project_key }} \
            -Dsonar.organization=${{ inputs.sonar_organization }} \
            -Dsonar.login=${{ secrets.token }}