name: License Compliance

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write

jobs:
  check_licences:
    uses: eclipse-ecsp/.github/workflows/workflow-licences-analysis.yml@main
    name: Analyse Licences
    with:
      create-review: false
    secrets:
      token: ${{ secrets.GITLAB_API_TOKEN }}
