name: Maven Build & Sonar Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  maven_build:
    uses: ./.github/workflows/maven-run.yml
    name: Maven Build
    with:
      maven_args: 'clean package --file pom.xml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  sonar_analysis:
    needs: maven_build
    uses: ./.github/workflows/sonar-analysis.yml
    secrets:
      token: ${{ secrets.SONAR_TOKEN }}
  dependencies_analysis:
    needs: sonar_analysis
    uses: ./.github/workflows/dependencies-analysis.yml
    permissions:
      pull-requests: write
      contents: read
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}