name: Maven Build & Sonar Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  maven_build:
    uses: ./.github/workflows/workflow-maven-run.yml
    name: Maven Build
    with:
      maven_args: 'clean package --file pom.xml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  sonar_analysis:
    needs: maven_build
    uses: ./.github/workflows/workflow-sonar-analysis.yml
    secrets:
      token: ${{ secrets.SONAR_TOKEN }}
  dependencies_update:
    needs: sonar_analysis
    uses: ./.github/workflows/workflow-dependencies-update.yml
    permissions:
      pull-requests: write
      contents: read
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  docker_push:
    needs: dependencies_update
    uses: ./.github/workflows/workflow-docker-push.yml
    secrets:
      token: ${{ secrets.DOCKER_API_TOKEN }}