name: Use SonarCloud Analysis Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  maven_build:
    uses: ./.github/workflows/maven-run.yml
    name: Maven Build
    with:
      java_version: '17'
      maven_args: 'clean package --file pom.xml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  sonar_analysis:
    needs: maven_build
    uses: ./.github/workflows/analyse.yml
    with:
      java_version: '17'
      sonar_project_key: 'eclipse-ecsp_helloWorldService'
      sonar_organization: 'eclipse-ecsp'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}