name: Release

on:
  release:
    types: [created]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-nodejs-build.yml@nodejs
    with:
      node-version: '20'

  license-check:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-nodejs-licence-analysis.yml@nodejs
    needs: build-and-test
    with:
      node-version: '20'
      java-version: '17'
      create-review: false
  
  extract-version:
    runs-on: ubuntu-latest
    needs: license-check
    name: Extract release version without v prefix
    outputs:
      release_version: ${{ steps.set_version.outputs.release_version }}
    steps:
      - id: set_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
              if [[ "${{ github.event.release.tag_name }}" == v* ]]; then
                  version=${{ github.event.release.tag_name }}
                  echo "release_version=${version:1}" >> $GITHUB_ENV
                  echo "::set-output name=release_version::${version:1}"
              else
                  echo "release_version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
                  echo "::set-output name=release_version::${{ github.event.release.tag_name }}"
              fi
          else
             version=$(node -p "require('./package.json').version")
            echo "release_version=${version}" >> $GITHUB_ENV
            echo "::set-output name=release_version::${version}" 
          fi

  docker-push:
    needs: [build-and-test, license-check, extract-version]
    uses: eclipse-ecsp/.github/.github/workflows/workflow-nodejs-docker-push.yml@nodejs
    with:
      registry: 'docker.io'
      image-name: 'hello-world-service'
      image-tag: ${{ needs.extract-version.outputs.release_version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_API_TOKEN: ${{ secrets.DOCKER_API_TOKEN }}
