name: Update Version

on:
  release:
    types: [created]

jobs:
  extract_version:
    runs-on: ubuntu-latest
    name: Extract release version without v prefix
    outputs:
      release_version: ${{ steps.set_version.outputs.release_version }}
    steps:
      - id: set_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
              if [[ "${{ github.event.release.tag_name }}" == v* ]]; then
                  version=${{ github.event.release.tag_name }}
                  echo "release_version=${version:1}" >> $GITHUB_ENV
                  echo "::set-output name=release_version::${version:1}"
              else
                  echo "release_version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
                  echo "::set-output name=release_version::${{ github.event.release.tag_name }}"
              fi
          else
            version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
            echo "release_version=$version" >> $GITHUB_ENV
            echo "::set-output name=release_version::$version"
          fi
  update_next_version:
    needs: extract_version
    uses: eclipse-ecsp/.github/.github/workflows/workflow-update-next-version.yml@version-update
    with:
      version: ${{ needs.extract_version.outputs.release_version }}
    secrets: inherit

