name: Update Version

on:
  release:
    types: [created]

jobs:
  update_next_version:
    uses: ./.github/workflows/workflow-update-next-version.yml
    with:
      version: ${{ inputs.version}}
    secrets: inherit

