name: Update Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  update_next_version:
    uses: ./.github/workflows/workflow-update-next-version.yml
    with:
      version: ${{ inputs.version}}
    secrets: inherit

