name: Update Version

on:
  release:
    types: [created]

jobs:
  update_next_version:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-update-next-version.yml@docker-push
    with:
      version: ${{ inputs.version}}
    secrets: inherit

