name: Update Project Version

on:
  workflow_call:
    inputs:
      version:
        description: 'The new version to set for the project'
        required: true
        type: string

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: update to release Version
        run: |
          mvn versions:set -DnewVersion=${{ inputs.version }} -DgenerateBackupPoms=false

      - name: update new snapshot version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT -DgenerateBackupPoms=false

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: update next version
        run: |
          git commit -am "chore(release): update to version ${{ inputs.version }}"
          git push origin ${{ github.ref }}