name: "Update DEPENDENCIES file"

on:
  workflow_call:
    inputs:
      java_version:
        description: "The Java version to use"
        required: false
        type: string
        default: "17"
    secrets:
      token:
        description: "The GitHub token for creating pull requests"
        required: true

jobs:
  analyse_and_update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'zulu'
          cache: maven

      - name: Generate Dependencies file
        run: mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES -P dash

      - name: Check if file was changed
        run: |
          if git diff --name-only | grep -e 'DEPENDENCIES'; then
            echo "The file was changed"
            echo "was_file_changed=true" >> "$GITHUB_ENV"
          else
            echo "The file was not changed"
            echo "was_file_changed=false" >> "$GITHUB_ENV"
          fi

      - name: Configure Git
        if: ${{ env.was_file_changed == 'true' }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create pull request
        if: ${{ env.was_file_changed == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            DEPENDENCIES
          token: ${{ secrets.token }}
          branch: chore/update-DEPENDENCIES
          commit-message: "chore(dependencies): Update DEPENDENCIES"
          delete-branch: true
          title: Update DEPENDENCIES
          body: |
            This PR updates the DEPENDENCIES